# Render.com Blueprint Configuration
# This file defines how to deploy your BookStore application on Render.com using Docker

# Database (PostgreSQL) - Must be created first
databases:
  - name: bookstore-db
    databaseName: bookstore
    user: bookstore_user
    region: ohio # or your preferred region

services:
  # Backend API Service (Docker)
  - type: web
    name: bookstore-api
    runtime: docker
    dockerfilePath: BookStore.API/Dockerfile
    dockerContext: BookStore.API
    region: ohio # should match database region
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore-db
          property: connectionString
      - key: JwtSettings__Secret
        generateValue: true
      - key: JwtSettings__Issuer
        value: BookStore.API
      - key: JwtSettings__Audience
        value: BookStore.Client
      - key: JwtSettings__ExpirationHours
        value: "24"
    healthCheckPath: /health
    
  # Frontend Static Site (Docker)
  - type: web
    name: bookstore-frontend
    runtime: docker
    dockerfilePath: BookStore-frontend/Dockerfile
    dockerContext: BookStore-frontend
    region: ohio
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: bookstore-api
          property: host
