services:
  # Backend API Service
  - type: web
    name: bookstore-api
    env: docker
    dockerfilePath: ./BookStore.API/Dockerfile
    dockerContext: ./BookStore.API
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        value: $DATABASE_URL
      - key: JwtSettings__Secret
        generateValue: true
      - key: JwtSettings__Issuer
        value: BookStore.API
      - key: JwtSettings__Audience
        value: BookStore.Client
      - key: JwtSettings__ExpirationHours
        value: "24"
        
  # Frontend Service
  - type: static
    name: bookstore-frontend
    rootDir: ./BookStore-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://bookstore-api.onrender.com/api

databases:
  - name: bookstore-db
    databaseName: bookstore
    user: bookstore_user
